### PR TITLE
Solved Issue#4: Added Tools Section to Navbar

### PR DESCRIPTION
**Pull request by SahilSingh177**
Here is the attached Demonstration.
https://user-images.githubusercontent.com/96344003/193426751-f7ac3708-16c9-4256-8a66-ac8be305e168.mp4

### CODE REVIEW

**Comment by PrerakMathur20** [comment]
Please upload the Demo again as this one is showing issues. If possible, also add some screenshots.

**Comment by SahilSingh177** [comment]
Demo Video -
https://user-images.githubusercontent.com/96344003/193431458-99fa4fdf-d766-4a66-b6fa-e69eca33fc82.mp4

Screenshots -
Screenshot (136)
Screenshot (137)

**Comment by SahilSingh177** [comment]
### Demo Video

 https://user-images.githubusercontent.com/96344003/193431647-d3288101-8e60-4d58-b134-9f5815eb0e2d.mov

### Screenshots

Screenshot (136)
Screenshot (137)

**Comment by PrerakMathur20** [comment]
LGTM!

**Comment by PrerakMathur20** [comment]
@SahilSingh177 
Kindly link the issues as in `Fixes #<Issue Number>` format in your description to effectively link them to the issue.

**Pull request merged**
